#!/bin/sh

set -ex

LOGO="content/logo.png"
#SIZES="16 24 32 57 72 96 114 128 195"
SIZES="16 24 32 57 72 96"

test -f $LOGO || exit 0

convert $LOGO						\
   -format 'roundrectangle 0,0 %[fx:w],%[fx:h] 64,64'	\
   info: >| rounded_corner.mvg
convert $LOGO			\
   -alpha transparent		\
   -background none		\
   -fill white			\
   -draw "@rounded_corner.mvg"	\
   rounded_corner_mask.png
convert $LOGO			\
   rounded_corner_mask.png	\
      -compose DstIn		\
      -composite		\
   rounded_border.png


for size in $SIZES; do
   convert rounded_border.png -resize ${size}x${size} favicon-${size}.png
done
convert favicon-*.png home/favicon.ico
rm favicon-*.png rounded_corner.mvg rounded_corner_mask.png rounded_border.png
