package Text::Highlight::Aldor;

use strict;
use warnings FATAL => 'all';
use utf8;

use base qw/Text::Highlight::Module/;

sub syntax {
   {
      'name' => 'Aldor',
      'case' => 1,
      'blockCommentOn' => [
      ],
      'blockCommentOff' => [
      ],
      'lineComment' => [
         '--',
         '++',
      ],
      'quot' => [
         '\'',
         '"',
      ],
      'escape' => '_',
      'continueQuote' => 0,
      'delimiters' => '(){};,:',
      'key1' => [
         ".",
         ",",
         ";",
         ":",
         "::",
         ":*",
         '$',
         '@',
         "|",
         "=>",
         "+->",
         ":=",
         "==",
         "==>",
         "'",
         "[",
         "]",
         "{",
         "}",
         "(",
         ")",
      ],
      'key2' => [
         "add",
         "and",
         "always",
         "assert",
         "break",
         "but",
         "catch",
         "default",
         "define",
         "delay",
         "do",
         "else",
         "except",
         "export",
         "extend",
         "fix",
         "for",
         "fluid",
         "free",
         "from",
         "generate",
         "goto",
         "has",
         "if",
         "import",
         "in",
         "inline",
         "is",
         "isnt",
         "iterate",
         "let",
         "local",
         "macro",
         "never",
         "not",
         "of",
         "or",
         "pretend",
         "ref",
         "repeat",
         "return",
         "rule",
         "select",
         "then",
         "throw",
         "to",
         "try",
         "where",
         "while",
         "with",
         "yield",
      ],
      'key3' => [
         qr/\b[A-Z][A-Za-z0-9]+\b/,
      ],
      'key4' => [
         'print',
         'stdin',
         'stdout',
         'stderr',
         'newline',
         'true',
         'false',
      ],
      'key5' => [
         '#include',
         '#library',
         '#pile',
         '#assert',
         '#unassert',
         '#if',
         '#endif',
      ],
      'key6' => [
         'by',
         'case',
         'mod',
         'quo',
         'rem',
         '#',
         '+',
         '-',
         '+-',
         '~',
         '^',
         '*',
         '**',
         '..',
         '=',
         '~=',
         '^=',
         '/',
         '/\\',
         '<',
         '<=',
         '<<',
         '<-',
         '\\',
         '\\/',
         '>',
         '>=',
         '>>',
         '->',
      ],
   }
}

1
