package Text::Highlight::CPP;

use strict;
use warnings FATAL => 'all';
use utf8;

use base qw/Text::Highlight::Module/;

sub syntax {
   {
      'name' => 'C/C++',
      'case' => 1,
      'blockCommentOn' => [
         '/*',
      ],
      'blockCommentOff' => [
         '*/',
      ],
      'lineComment' => [
         '//',
      ],
      'quot' => [
         '\'',
         '"',
      ],
      'escape' => '\\',
      'continueQuote' => 0,
      'delimiters' => ',(){}[]-+*%/="\'~!&|<>?:;.#',
      'key1' => [
         '__based',
         'if',
         'sizeof',
         'new',
         'this',
         'break',
         'for',
         'private',
         'default',
         'else',
         '__pascal',
         'delete',
         'continue',
         '__fastcall',
         '__cdecl',
         'friend',
         '__inline',
         'do',
         '__virtual_inheritance',
         'case',
         '__multiple_inheritance',
         'operator',
         'static_cast',
         'dynamic_cast',
         'const_cast',
         'reinterpret_cast',
         '__asm',
         'asm',
         'public',
         'goto',
         '__single_inheritance',
         'throw',
         'namespace',
         'protected',
         'return',
         'while',
         'try',
         'switch',
         'catch',
      ],
      'key2' => [
         'ifndef',
         'elif',
         'undef',
         'ifdef',
         'include',
         'else',
         'define',
         'if',
         'pragma',
         'error',
         'endif',
         'line',
      ],
      'key3' => [
         'uint64_t',
         'int64_t',
         'uint32_t',
         'int32_t',
         'uint16_t',
         'int16_t',
         'uint8_t',
         'int8_t',
         'ptrdiff_t',
         'intptr_t',
         'ssize_t',
         'size_t',
         'char',
         'auto',
         'register',
         'signed',
         'unsigned',
         'virtual',
         'volatile',
         'float',
         'extern',
         'template',
         'class',
         'explicit',
         'static',
         'typedef',
         'inline',
         'typename',
         'const',
         'bool',
         'double',
         'union',
         'void',
         'short',
         'struct',
         'enum',
         'int',
         'long',
      ],
      'key4' => [
         'true',
         'false',
         'stdin',
         'stdout',
         'stderr',
         'NULL',
      ],
      key5 => [
         'cout',
         'cerr',
         'cin',
      ],
   }
}

1
