package Text::Highlight::HTML;

use strict;
use warnings FATAL => 'all';
use utf8;

use base qw/Text::Highlight::Module/;

#TODO:
# 1) DONE - Convert some tag list into a hashref syntax tree for sub syntax
# 2) More distant goal: rewrite this not using HTML::SyntaxHighlighter
#    as I'm not much of a fan of its highlighting method. I'd prefer
#    html tags one color, attrib names another, and attrib vals as 
#    strings. This wouldn't highlight the </> around the tags. Maybe 
#    this is just how whatever text editors I've used have done it, 
#    but it feels more "right".
#
#    At the very least, I'd keep an option for using it as-is. This
#    means creating some kind of optional "options" hashref that gets
#    passed to individual T::H::foo methods. Maybe have one all should
#    implement that uses the method builtin to T::H itself. Got some
#    other shit to iron out first.
# 3) Looks like this method is html-escaping all text, which may not 
#    be the desired escape method. Something else to look into when 
#    poking here again.

#array of types, allows for span tag nesting
my @types = ();

#HTML::SyntaxHighlighter to Text::Highlight class translations
my %classes = (
   'D' => 'key4',   #DTD
   'H' => 'key3',   #html/head/body
   'B' => 'key1',   #block
   'I' => 'key2',   #inline
   'A' => 'string', #attribute values
   'T' =>  undef,   #text
   'S' => 'key5',   #script/style
   'C' => 'comment',
);

sub highlight {
   my ($class, $obj, $code) = @_;
   
   eval {
      require HTML::SyntaxHighlighter; 
      require HTML::Parser;
   };
   if ($@) {
      $obj->{_active} = $class->syntax;
      $obj->_highlight($code);
      return;
   }
   
   my $out;
   my $p = HTML::SyntaxHighlighter->new (br => "", out_func => \$out);
   $p->parse($code);
   
   #HTML::Entity's decode_entities method doesn't seem to convert nbsp's into spaces
   # (and some lazy html omits the semi-colon)
   $out =~ s/&nbsp;?/ /g;
   
   HTML::Parser->new (
      api_version => 3,
      handlers    => {
         start => [\&start, 'tagname,attr'],
         end   => [\&end,   'tagname'],
         #colorize the decoded text as the type on top of the @types stack
         text => [ sub { $obj->_colorize ($types[-1], shift) }, 'dtext'],

      },
   )->parse ($out);
}

#if it's a span tag, look up the tag's class for its Highlighter type and push it on the stack
sub start {
   return if shift ne 'span';
   my $attr = shift;
   push @types, exists $classes{$attr->{class}} ? $classes{$attr->{class}} : undef;
}

#if it's a span tag, pop the top type off the stack
sub end {
   pop @types if shift eq 'span';
}

sub syntax {
   {
      'name' => 'HTML',
      'case' => 0,
      'blockCommentOn' => [
         '<!--',
      ],
      'blockCommentOff' => [
         '-->',
      ],
      'lineComment' => [],
      'quot' => [
         '\'',
         '"',
      ],
      'escape' => '\\',
      'continueQuote' => 0,
      'delimiters' => '<>/%="\',.(){}[]+*~&|;',
      'key3' => [
         'ne',
         'le',
         'para',
         'Xi',
         'Nu',
         'dArr',
         'Oacute',
         'Omega',
         'Prime',
         'pound',
         'Igrave',
         'THORN',
         'forall',
         'emsp',
         'lowast',
         'brvbar',
         'alefsym',
         'nbsp',
         'Delta',
         'clubs',
         'quot',
         'cedil',
         'and',
         'plusmn',
         'ge',
         'uml',
         'raquo',
         'equiv',
         'laquo',
         'rdquo',
         'divide',
         'fnof',
         'Chi',
         'Iacute',
         'Sigma',
         'acute',
         'frac34',
         'upsih',
         'lrm',
         'part',
         'exist',
         'nabla',
         'image',
         'prop',
         'Omicron',
         'zwj',
         'gt',
         'Aacute',
         'bsub',
         'weierp',
         'rsquo',
         'otimes',
         'Kappa',
         'thetasym',
         'hArr',
         'Ograve',
         'sdot',
         'copy',
         'oplus',
         'Acirc',
         'Zeta',
         'sup',
         'crarr',
         'lsquo',
         'bdquo',
         'apos',
         'Eacute',
         'Egrave',
         'lceil',
         'piv',
         'ldquo',
         'cent',
         'uArr',
         'hellip',
         'ensp',
         'sect',
         'AElig',
         'curren',
         'ordf',
         'sbquo',
         'macr',
         'Rho',
         'sup2',
         'euro',
         'Aring',
         'mdash',
         'Otilde',
         'Uuml',
         'Eta',
         'uacute',
         'agrave',
         'notin',
         'ndash',
         'sube',
         'szlig',
         'micro',
         'not',
         'sup1',
         'middot',
         'Ecirc',
         'Iota',
         'lsaquo',
         'thinsp',
         'sum',
         'Ntilde',
         'Scaron',
         'Atilde',
         'cap',
         'lang',
         'isin',
         'Gamma',
         'Upsilon',
         'ang',
         'hearts',
         'spades',
         'Dagger',
         'int',
         'rlm',
         'infin',
         'Ugrave',
         'Oslash',
         'rsaquo',
         'Alpha',
         'Mu',
         'ni',
         'real',
         'bull',
         'Beta',
         'Icirc',
         'ETH',
         'prod',
         'larr',
         'ordm',
         'perp',
         'reg',
         'Ucirc',
         'Psi',
         'tilde',
         'zwnj',
         'asymp',
         'deg',
         'times',
         'sim',
         'circ',
         'Theta',
         'sup3',
         'Tau',
         'frac14',
         'OElig',
         'diams',
         'shy',
         'or',
         'Phi',
         'Iuml',
         'rfloor',
         'iexcl',
         'Ccedil',
         'cong',
         'frac12',
         'rArr',
         'loz',
         'cup',
         'radic',
         'Euml',
         'frasl',
         'lt',
         'Lamdba',
         'there4',
         'Ouml',
         'oline',
         'Yacute',
         'amp',
         'Auml',
         'sigmaf',
         'permil',
         'iquest',
         'Pi',
         'empty',
         'supe',
         'yen',
         'rang',
         'trade',
         'minus',
         'lfloor',
         'sub',
         'Epsilon',
         'Yuml',
         'Ocirc'
      ],
      'key2' => [
         'http-equiv',
         'content',
         'clear',
         '#IMPLIED',
         'target',
         'onkeydown',
         'onkeyup',
         'onmouseup',
         'scope',
         'onmouseover',
         'lang',
         'align',
         'valign',
         'IDREF',
         'name',
         'scheme',
         'charset',
         'prompt',
         '#PCDATA',
         'frameborder',
         'onmousedown',
         'rev',
         'title',
         'span',
         'onclick',
         'start',
         'width',
         'vlink',
         'usemap',
         'nowrap',
         'coords',
         'frame',
         'size',
         'onblur',
         'dir',
         'datetime',
         'face',
         'color',
         'summary',
         'html',
         '-//W3C//DTD XHTML 1.0 Transitional//EN',
         'bgcolor',
         'text',
         'vspace',
         'tabindex',
         'standby',
         'language',
         'style',
         'onmousemove',
         'background',
         'height',
         '-//W3C//DTD XHTML 1.0 Frameset//EN',
         'codetype',
         'char',
         'multiple',
         'codebase',
         'rel',
         'profile',
         'xmlns',
         '#FIXED',
         '#REQUIRED',
         'ondblclick',
         'axis',
         'marginwidth',
         'cols',
         'readonly',
         'onchange',
         '-//W3C//DTD XHTML 1.0 Strict//EN',
         'abbr',
         'media',
         'href',
         'id',
         'NMTOKEN',
         'compact',
         'value',
         'src',
         'for',
         'data',
         'xml:space',
         'hreflang',
         'checked',
         'declare',
         'onkeypress',
         'http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd',
         'type',
         'shape',
         'label',
         'class',
         'accesskey',
         'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd',
         'object',
         'disabled',
         'headers',
         'scrolling',
         'noresize',
         'rules',
         'rows',
         'CDATA',
         'onfocus',
         'alink',
         'rowspan',
         'colspan',
         'defer',
         'slign',
         'cellspacing',
         'PUBLIC',
         'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd',
         'EMPTY',
         'charoff',
         'cite',
         'marginheight',
         'maxlength',
         'link',
         'onselect',
         'archive',
         'alt',
         'accept',
         'longdesc',
         'classid',
         'onmouseout',
         'xml:lang',
         'border',
         'noshade',
         'onunload',
         'hspace',
         'onload',
         'valuetype',
         'cellpadding',
         'selected',
      ],
      'key1' => [
         'tr',
         'strike',
         'input',
         '!ENTITY',
         'table',
         'form',
         'h5',
         'meta',
         'map',
         'isindex',
         'tfoot',
         'caption',
         'code',
         'base',
         'br',
         'acronym',
         'strong',
         'h4',
         'em',
         'q',
         'b',
         'title',
         'span',
         'applet',
         'small',
         'area',
         'frame',
         'dir',
         'body',
         'ol',
         'html',
         'var',
         'ul',
         '?xml',
         'del',
         'blockquote',
         'style',
         'iframe',
         'dfn',
         'h3',
         'textarea',
         'a',
         'img',
         'tt',
         'font',
         'noframes',
         'thead',
         'u',
         'abbr',
         'sup',
         'h6',
         'address',
         'param',
         'basefont',
         'th',
         'h1',
         'head',
         'tbody',
         'legend',
         'dd',
         's',
         '!DOCTYPE',
         'hr',
         '!ATTLIST',
         'li',
         'td',
         'label',
         'dl',
         'kbd',
         'object',
         'div',
         'dt',
         'pre',
         'center',
         '!ELEMENT',
         'samp',
         'col',
         'option',
         'cite',
         'select',
         'i',
         'link',
         'script',
         'bdo',
         'menu',
         'colgroup',
         'h2',
         'ins',
         'p',
         'sub',
         'big',
         'fieldset',
         'frameset',
         'button',
         'noscript',
         'optgroup',
      ],
   }
}

1
